/*!
	@file		AudioConverter.h
	@framework	AudioToolbox.framework
	@copyright	(c) 1985-2015 by Apple, Inc., all rights reserved.
    @abstract   API's to perform audio format conversions.
    
	AudioConverters convert between various linear PCM and compressed
	audio formats. Supported transformations include:

	- PCM float/integer/bit depth conversions
	- PCM sample rate conversion
	- PCM interleaving and deinterleaving
	- encoding PCM to compressed formats
	- decoding compressed formats to PCM

	A single AudioConverter may perform more than one
	of the above transformations.
*/

using System.Runtime.Versioning;

namespace NAudio.MacOS.AudioToolbox.Interop;

/// <summary>
/// Dithering algorithms for audio converters <br />
/// Constants to be used as the value for kAudioConverterPropertyDithering.
/// </summary>
[SupportedOSPlatform("macos")]
[UnsupportedOSPlatform("ios")]
public enum AudioConverterDitheringAlgorithm : uint
{
    /// <summary>
    /// No dithering algorithm is selected. This is the default value.
    /// </summary>
    None = 0,
    /// <summary>
    /// Dither signal is generated by a white noise source with a triangular probability density function
    /// </summary>
    TPDF = 1,
    /// <summary>
    /// Use a static, perceptually weighted noise shaped dither
    /// </summary>
	NoiseShaping = 2
}