// This interop definition was derived from the file AudioConverter.h of the Audio Toolbox Framework.
// See https://developer.apple.com/documentation/audiotoolbox for more information.

using System.Runtime.Versioning;

namespace NAudio.MacOS.AudioToolbox;

/// <summary>
/// Dithering algorithms for audio converters <br />
/// Constants to be used as the value for kAudioConverterPropertyDithering.
/// </summary>
[SupportedOSPlatform("macos")]
[UnsupportedOSPlatform("ios")]
public enum AudioConverterDitheringAlgorithm : uint
{
    /// <summary>
    /// No dithering algorithm is selected. This is the default value.
    /// </summary>
    None = 0,
    /// <summary>
    /// Dither signal is generated by a white noise source with a triangular probability density function
    /// </summary>
    TPDF = 1,
    /// <summary>
    /// Use a static, perceptually weighted noise shaped dither
    /// </summary>
	NoiseShaping = 2
}