namespace NAudio.Utils
{
    partial class HResult
    {
        /// <summary>
        /// Facility codes that are contained in an HRESULT numeric value.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Design",
            "CA1069:Enums values should not be duplicated",
            Justification = "Facility codes are constant values in Windows C headers. We can't emulate these as global constants so adding these to an enumeration.")]
        public enum Facility : System.Int32
        {
#pragma warning disable 1591
            NULL,
            RPC,
            DISPATCH,
            STORAGE,
            ITF,
            WIN32 = 7,
            WINDOWS = 8,
            SSPI = 9,
            SECURITY = 9,
            CONTROL,
            CERT,
            INTERNET,
            MEDIASERVER,
            MSMQ,
            SETUPAPI,
            SCARD,
            COMPLUS,
            AAF,
            URT,
            ACS,
            DPLAY,
            UMI,
            SXS,
            WINDOWS_CE,
            HTTP,
            USERMODE_COMMONLOG,
            WER,
            USERMODE_FILTER_MANAGER = 31,
            BACKGROUNDCOPY,
            CONFIGURATION,
            WIA,
            STATE_MANAGEMENT,
            METADIRECTORY,
            WINDOWSUPDATE,
            DIRECTORYSERVICE,
            GRAPHICS,
            SHELL = 39,
            NAP = 39,
            TPM_SERVICES,
            TPM_SOFTWARE,
            UI,
            XAML,
            ACTION_QUEUE,
            PLA = 48,
            WINDOWS_SETUP = 48,
            FVE,
            FWP,
            WINRM,
            NDIS,
            USERMODE_HYPERVISOR,
            CMI,
            USERMODE_VIRTUALIZATION,
            USERMODE_VOLMGR,
            BCD,
            USERMODE_VHD,
            USERMODE_HNS,
            SDIAG,
            WEBSERVICES = 61,
            WINPE = 61,
            WPN,
            WINDOWS_STORE,
            INPUT,
            QUIC,
            EAP,
            WINDOWS_DEFENDER = 80,
            OPC,
            XPS,
            RAS,
            MBN = 84,
            POWERSHELL = 84,
            P2P_INT = 98,
            P2P,
            DAF,
            BLUETOOTH_ATT,
            AUDIO,
            STATEREPOSITORY,
            VISUALCPP = 109,
            SCRIPT = 112,
            PARSE,
            BLB = 120,
            BLB_CLI,
            WSBAPP,
            BLBUI = 128,
            USN,
            USERMODE_VOLSNAP,
            TIERING,
            WSB_ONLINE = 133,
            ONLINE_ID,
            DEVICE_UPDATE_AGENT,
            DRVSERVICING,
            DLS = 153,
            DELIVERY_OPTIMIZATION = 208,
            USERMODE_SPACES = 231,
            USER_MODE_SECURITY_CORE,
            USERMODE_LICENSING = 234,
            SOS = 160,
            DEBUGGERS = 176,
            SPP = 256,
            RESTORE = 256,
            DMSERVER = 256,
            DEPLOYMENT_SERVICES_SERVER,
            DEPLOYMENT_SERVICES_IMAGING,
            DEPLOYMENT_SERVICES_MANAGEMENT,
            DEPLOYMENT_SERVICES_UTIL,
            DEPLOYMENT_SERVICES_BINLSVC,
            DEPLOYMENT_SERVICES_PXE = 263,
            DEPLOYMENT_SERVICES_TFTP,
            DEPLOYMENT_SERVICES_TRANSPORT_MANAGEMENT = 272,
            DEPLOYMENT_SERVICES_DRIVER_PROVISIONING = 278,
            DEPLOYMENT_SERVICES_MULTICAST_SERVER = 289,
            DEPLOYMENT_SERVICES_MULTICAST_CLIENT,
            DEPLOYMENT_SERVICES_CONTENT_PROVIDER = 293,
            LINGUISTIC_SERVICES = 305,
            AUDIOSTREAMING = 1094,
            TTD = 1490,
            ACCELERATOR = 1536,
            WMAAECMA = 1996,
            DIRECTMUSIC = 2168,
            DIRECT3D10,
            DXGI,
            DXGI_DDI,
            DIRECT3D11,
            DIRECT3D11_DEBUG,
            DIRECT3D12,
            DIRECT3D12_DEBUG,
            DXCORE,
            LEAP = 2184,
            AUDCLNT,
            WINCODEC_DWRITE_DWM = 2200,
            WINML = 2192,
            DIRECT2D = 2201,
            DEFRAG = 2304,
            USERMODE_SDBUS,
            JSCRIPT,
            PIDGENX = 2561,
            EAS = 85,
            WEB = 885,
            WEB_SOCKET,
            MOBILE = 1793,
            SQLITE = 1967,
            UTC = 1989,
            WEP = 2049,
            SYNCENGINE,
            XBOX = 2339,
            GAME,
            PIX = 2748
#pragma warning restore 1591
        }
    }
}
